### ISSUE TITLE
fix: nested data definition from YAML data

### ISSUE THREAD

**Issue by Tahul** [nuxt-themes/docus#300]
Currently we do not support nested objects from YAML data definition in Markdown.

What is used right now:

```
secondary: {
  type: Array,
  default: () => ['Open on GitHub', 'https://github.com']
}
```

^ Props

```
:::pre-launch-hero{yml}
title: Hello
description: Description
cta:
  - Get started
  - /get-started/installation
secondary:
  - Open on GitHub
  - https://github.com/nuxtlabs/docus
:::
```

^ Syntax (see secondary)

It should work this way instead:

```
secondary: {
  type: Array,
  default: () => ({ label: 'Open on GitHub', to: 'https://github.com/nuxtlabs/docus' })
}
```

^ Props

```
:::pre-launch-hero{yml}
title: Hello
description: Description
cta:
  label: Get started
  to: /get-started/installation
secondary:
  label: Open on GitHub
  to: https://github.com/nuxtlabs/docus
:::
```

^ Syntax (see secondary)
