### ISSUE TITLE
[dx] flatten markdown meta

### ISSUE THREAD

**Issue by pi0** [nuxt-themes/docus#324]
### Is your feature request related to a problem? Please describe.

Using yml tabs can be tricky! For defining common meta like `navigation.title`, it could be nice providing a flatten shortcut to reduce verbosity of meta.

### Describe the solution you'd like

Instead of:

```yml
title: Vercel Provider
description: Optimize images at Vercel's Edge Network
navigation:
  title: Vercel
```

Allow:

```yml
title: Vercel Provider
navigation.title: Vercel
description: Optimize images at Vercel's Edge Network
```

This can be possible by running an object through [flat.unflatten](https://www.npmjs.com/package/flat).

### Describe alternatives you've considered

Supporting simpler shortcuts like `nav_title`:

```yml
title: Vercel Provider
nav_title: Vercel
description: Optimize images at Vercel's Edge Network
```

Or combined json: (which is possible as of now)

```yml
title: Vercel Provider
navigation: { title: "Vercel" }
description: Optimize images at Vercel's Edge Network
```
