### ISSUE TITLE
HMR not working at WSL, Docker or VirtualBox (vboxsf fs type)

### ISSUE THREAD

**Issue by Rekryt** [nuxt-themes/docus#687]
HMR not working at some fs configurations like WSL or Docker then i try modify files in `/content/` folder.

To solve this problem usually uses "file system polling".
In vite configuration: https://vitejs.dev/config/server-options.html#server-watch helps `server.watch.usePolling = true`
https://github.com/paulmillr/chokidar#performance

My nuxt.config.ts
```
export default defineNuxtConfig({
    extends: '@nuxt-themes/docus',
    content: {
        watch: {
            ws: {
                hostname: process.env.NUXT_WS_PROXY_HOST || 'localhost',
            },
        },
    },
    vite: {
        server: {
            watch: {
                usePolling: true,
            },
        },
    },
});

```

Dockerfile
```
FROM node:18.12.0-alpine

# create destination directory
RUN mkdir -p /home/nuxt
WORKDIR /home/nuxt

# copy the app, note .dockerignore
COPY . /home/nuxt/
RUN npm install
RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start" ]
```

.env
```
COMPOSE_PROJECT_NAME=docs
NUXT_WS_PROXY_HOST=192.168.1.227
NUXT_HOST=0.0.0.0
NUXT_PORT=3000
# Create one with no scope selected on https://github.com/settings/tokens/new
# This token is used for fetching the repository releases.
GITHUB_TOKEN=
```

docker-compose.dev.yml
```
version: '3'
services:
    docs:
        restart: unless-stopped
        build:
            context: .
        volumes:
            - ./.nuxt/:/home/nuxt/.nuxt/
            - ./content/:/home/nuxt/content/
            - ./nuxt.config.ts:/home/nuxt/nuxt.config.ts
            - ./app.config.ts:/home/nuxt/app.config.ts
        network_mode: host
        ports:
            - 3000:3000
            - 4000:4000
            - 24678:24678
        env_file:
            - .env
        command: ["npm", "run", "dev"]
```

My be content.watch.<some params> can helps? How to get fs polling for `/content/` folder?

Not have parameter `poll` or `usePolling` in the documentation:
https://content.nuxtjs.org/api/configuration/#watch
Similar problem:
https://github.com/nuxt/nuxt.js/issues/2481
