### ISSUE TITLE
If I deploy manually

### ISSUE THREAD

**Issue by DrAugus** [nuxt-themes/docus#796]
If I deploy manually, all my pages become **404**.  
cause there is a lot of json missing in [`/api/_content/query/`](https://github.com/augusmeow/code/tree/gh-pages/api/_content/query), but why?  
Is there something wrong with my deploy.yml?

- site preview: [home](https://augusmeow.github.io/code/), [all 404](https://augusmeow.github.io/code/cpp)
- source repo: [link](https://github.com/DrAugus/draugus.github.io/tree/master/code)
- deploy repo: [link](https://github.com/augusmeow/code)

my root dir is `/code/`

```ts [nuxt.config.ts]
export default defineNuxtConfig({
  extends: '@nuxt-themes/docus',
  app: {
    baseURL: '/code/',
  },
})
```

here is my deploy yml: [full deploy-code.yml](https://github.com/DrAugus/draugus.github.io/blob/master/.github/workflows/deploy-code.yml)

```yml
name: Deploy to GitHub Pages
uses: crazy-max/ghaction-github-pages@v3.1.0
with:
    repo: ${{ matrix.deploy-user }}/${{ matrix.deploy-repo }}
    target_branch: gh-pages
    build_dir: ${{ matrix.deploy-dir }}
    jekyll: false
env:
    GH_PAT: ${{ secrets.DEPLOY_GH }}
```

```txt
deploy-dir: [code/.output/public]
deploy-user: [augusmeow]
deploy-repo: [code]
```
